name: newrecipe
on: [push]
jobs:
  convertrecipesintohtml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run:  php rezeptcreator.php 
        uses: docker://php
      - uses: crazy-max/ghaction-github-pages@v2.3.0
        if: success()
        with:
          target_branch: gh-pages
          build_dir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
