name: newrecipe
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - gh-pages
jobs:
  convertrecipesintohtml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mfinelli/setup-imagemagick@v1
      - run: convert recipes/images/Champignoncurry.jpg -resize '640x378^' recipes/images/Champignoncurryneu.jpg
      #- run: for file_name in recipes/images/*.jpg; do magick input.jp -resize 640x378 output.jpg
      #- uses: nanasess/setup-php@master
      #- run : php deployment/emptythefile.php
      #- run: for file_name in json/*.json; do php deployment/rezeptcreator.php "$file_name"; done
      #- run: for file_name in json/*.json; do php deployment/allrecipesintohtml.php "$file_name"; done
      #- run: php deployment/indexhtmlcreator.php
      - uses: crazy-max/ghaction-github-pages@v2.3.0
        if: success()
        with:
          target_branch: gh-pages
          build_dir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
